version: "3"

services:
  # PaperMC minecraft service
  papermc:
    build:
      context: .
      args:
        - MINECRAFT_VER=1.21.1
        - PAPER_BUILD=64
        - JAVA_VER=21

    ports:
      - 25565:25565

    environment:
      EULA: ${EULA}
      MEM: ${MEM}
      RCON: true
      RCON_PASS: ${RCON_PASS}

    volumes:
      - /data:./data

  s3-backup:
    image: peterrus/s3-cron-backup:latest

    environment:
      AWS_ACCESS_KEY_ID: ${S3_ID}
      AWS_SECRET_ACCESS_KEY: ${S3_SECRET}
      S3_BUCKET_URL: ${S3_BUCKET_URL}
      AWS_DEFAULT_REGION: ${S3_REGION}
      CRON_SCHEDULE: ${BACKUP_SCHEDULE}
      BACKUP_NAME: ${BACKUP_NAME}
      S3_ENDPOINT: ${S3_ENDPOINT}
      TARGET: ${TARGET}

    volumes:
      - /data:./data
